export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_ON_REFRESH = 'GET_USERS_LIST_ON_REFRESH';
export const ADD_TO_BOOKMARK_LIST = 'ADD_TO_BOOKMARK_LIST';
export const REMOVE_FROM_BOOKMARK_LIST = 'REMOVE_FROM_BOOKMARK_LIST';
